//grades.js
//version 1.10
//defines each grade and their parameters.
const opsExcessHoursThreshold = 4
const driverExcessHoursThreshold = 3

const grades = {
    //DRIVING GRADES
    "spot" : {
        "name" : "Qualified Driver (SPOT)",
        "shortname": "SPOT",
        "payCode": "OJJ",
        "group": "Driver",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  true,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OJJ,
        "earlyShiftRates": earlyShiftRatesLoco,
        "afternoonShiftRates": afternoonShiftRatesLoco,
        "nightShiftRates": nightShiftRatesLoco,
        "colour": "#4691db",
        "startDate": "",
        "endDate": ""
    },
    "level1" : {
        "name" : "Train Driver Level 1",
        "shortname": "TD Lvl 1",
        "payCode": "OJH",
        "group": "Driver",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  true,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OJH,
        "earlyShiftRates": earlyShiftRatesLoco,
        "afternoonShiftRates": afternoonShiftRatesLoco,
        "nightShiftRates": nightShiftRatesLoco,
        "colour": "rgb(114, 99, 191)",
        "startDate": "",
        "endDate": ""
    },
    "trainee" : {
        "name" : "Trainee Driver",
        "shortname": "Trainee",
        "payCode": "OJG",
        "group": "Driver",
        "ordinaryDays" : 10,
        "ordinaryHours" : 7.6,
        "ddo" : false,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OJG,
        "earlyShiftRates": earlyShiftRatesLoco,
        "afternoonShiftRates": afternoonShiftRatesLoco,
        "nightShiftRates": nightShiftRatesLoco,
        "colour": "rgb(56, 149, 149)",
        "startDate": "",
        "endDate": ""
    },
    "conversion" : {
        "name" : "Conversion Trainee Driver",
        "shortname": "Conversion",
        "payCode": "OJB",
        "group": "Driver",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  true,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OJB,
        "earlyShiftRates": earlyShiftRatesLoco,
        "afternoonShiftRates": afternoonShiftRatesLoco,
        "nightShiftRates": nightShiftRatesLoco,
        "colour": "rgb(207, 133, 50)",
        "startDate": "",
        "endDate": ""
    },
    "so8" : {
        "name" : "Train Services Officer SO-8",
        "shortname": "TSO SO-8",
        "payCode": "OGH",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGH,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    "so9" : {
        "name" : "Train Services Officer SO-9",
        "shortname": "TSO SO-9",
        "payCode": "OGI",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGI,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    "so10" : {
        "name" : "Train Services Officer SO-10",
        "shortname": "TSO SO-10",
        "payCode": "OGJ",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGJ,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    "so11" : {
        "name" : "Train Services Officer SO-11",
        "shortname": "TSO SO-11",
        "payCode": "OGK",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGK,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    "so12" : {
        "name" : "Train Services Officer SO-12",
        "shortname": "TSO SO-12",
        "payCode": "OGL",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGL,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    "so13" : {
        "name" : "Train Services Officer SO-13",
        "shortname": "TSO SO-13",
        "payCode": "OGM",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGM,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    //DAOS AND ROSTERS
    "dao" : {
        "name" : "Driver Allocation Officer",
        "shortname": "DAO",
        "payCode": "OGB",
        "group": "DAOs and Rosters",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": false,
        "suburbanAllowance":  false,
        "excessHoursThreshold": 4,
        "payRates": OGB,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(157, 29, 29)",
        "startDate": "",
        "endDate": ""
    },
    "daoteamleader" : {
        "name": "DAO Team Leader",
        "shortname": "DAO TL",
        "payCode": "OGI",
        "group": "DAOs and Rosters",
        "ordinaryDays": 9,
        "ordinaryHours": 8.5,
        "ddo": false,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": false,
        "suburbanAllowance":  false,
        "excessHoursThreshold": 4,
        "payRates": OGI,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(157, 29, 29)",
        "startDate": "",
        "endDate": ""
    },
    "driverrosters" : {
        "name": "Driver Rosters",
        "shortname": "Rosters",
        "payCode": "OGD",
        "group": "DAOs and Rosters",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": false,
        "suburbanAllowance":  false,
        "excessHoursThreshold": 4,
        "payRates": OGD,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(157, 29, 29)",
        "startDate": "",
        "endDate": ""
    },
    
    //SIGNALLING GRADES
    "sigso2" : {
        "name": "Signaller - Reliever (entry)",
        "shortname": "Sig Rel 1",
        "payCode": "OAO",
        "group": "Signallers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "signallers",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAO,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "sigso3" : {
        "name": "Signaller - Reliever",
        "shortname": "Sig Rel 2",
        "payCode": "OAQ",
        "group": "Signallers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "signallers",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAQ,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "acsm5" : {
        "name": "Area Controller (entry)",
        "shortname": "AC Entry",
        "payCode": "OAB",
        "group": "Signallers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "signallers",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAB,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "acsm6" : {
        "name": "Area Controller (complex)",
        "shortname": "AC Complex",
        "payCode": "OAD",
        "group": "Signallers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "signallers",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAD,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "dc" : {
        "name": "Depot Controller",
        "shortname": "DC",
        "payCode": "OAF",
        "group": "Signallers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "signallers",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAF,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },

    //TRAIN CONTROLLERS
    "tc1" : {
        "name": "Train Controller 1",
        "shortname": "TC1",
        "payCode": "OAH",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAH,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "tc2" : {
        "name": "Train Controller 2",
        "shortname": "TC2",
        "payCode": "OAI",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAI,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "tc3" : {
        "name": "Train Controller 3",
        "shortname": "TC3",
        "payCode": "OAJ",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAJ,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "tc4" : {
        "name": "Train Controller 4",
        "shortname": "TC4",
        "payCode": "OAL",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAL,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "fc" : {
        "name": "Fleet Controller",
        "shortname": "Fleet",
        "payCode": "OAK",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAK,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "pids1" : {
        "name": "PIDS Operator Div1",
        "shortname": "PIDS1",
        "payCode": "OAS",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAS,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "pids2" : {
        "name": "PIDS Operator Div2",
        "shortname": "PIDS2",
        "payCode": "OAR",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAR,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },

    //STATIONS
    "traineeStationAssistant" : {
        "name": "Trainee Station Assistant",
        "shortname": "Trainee SA",
        "payCode": "OBK",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OBK,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "stationAssistant" : {
        "name": "Station Assistant",
        "shortname": "SA",
        "payCode": "OBL",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OBL,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "stationOfficer" : {
        "name": "Station Officer",
        "shortname": "SO",
        "payCode": "OBU",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OBU,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "seniorStationOfficer" : {
        "name": "Senior Station Officer",
        "shortname": "Senior SO",
        "payCode": "OBW",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OBW,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "traineeStationMaster" : {
        "name": "Trainee Station Master",
        "shortname": "Trainee SM",
        "payCode": "OCB",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OCB,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "stationMaster" : {
        "name": "Station Master",
        "shortname": "SM",
        "payCode": "OCF",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OCF,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "seniorStationMaster" : {
        "name": "Senior Station Master",
        "shortname": "Senior SM",
        "payCode": "OCJ",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OCJ,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    //Legacy Stations Grades - EBA 2019 and earlier
    "sac1y1" : {
        "name": "Station Assistant 1 Year 1",
        "shortname": "SA1 Yr1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": saC1Y1Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "sac1y2" : {
        "name": "Station Assistant 1 Year 2",
        "shortname": "SA1 Yr2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": saC1Y2Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "sac1y3" : {
        "name": "Station Assistant 1 Year 3",
        "shortname": "SA1 Yr3",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": saC1Y3Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "sac2y1" : {
        "name": "Station Assistant 2 Year 1",
        "shortname": "SA2 Yr1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": saC2Y1Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    }
    ,
    "sac2y2" : {
        "name": "Station Assistant 2 Year 2",
        "shortname": "SA2 Yr2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": saC2Y2Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    }
    ,
    "sac2y3" : {
        "name": "Station Assistant 2 Year 3",
        "shortname": "SA2 Yr3",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": saC2Y3Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "sac3y1" : {
        "name": "Station Assistant 3 Year 1",
        "shortname": "SA3 Yr1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": saC3Y1Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "sac3y2" : {
        "name": "Station Assistant 3 Year 2",
        "shortname": "SA3 Yr2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": saC3Y2Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "sac3y3" : {
        "name": "Station Assistant 3 Year 3",
        "shortname": "SA3 Yr3",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": saC3Y3Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "lsay1" : {
        "name": "Leading Station Assistant Year 1",
        "shortname": "LSA Yr1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": lsaY1Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "lsay2" : {
        "name": "Leading Station Assistant Year 2",
        "shortname": "LSA Yr2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": lsaY2Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "lsay3" : {
        "name": "Leading Station Assistant Year 3",
        "shortname": "LSA Yr3",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": lsaY3Rates,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "soc1d1" : {
        "name": "Station Officer 1 Div 1",
        "shortname": "SO1 Div1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": soC1D1Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "soc1d2" : {
        "name": "Station Officer 1 Div 2",
        "shortname": "SO1 Div2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": soC1D2Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "soc2d1" : {
        "name": "Station Officer 2 Div 1",
        "shortname": "SO2 Div1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": soC2D1Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "soc2d2" : {
        "name": "Station Officer 2 Div 2",
        "shortname": "SO2 Div2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": soC2D2Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "soc3d1" : {
        "name": "Station Officer 3 Div 1",
        "shortname": "SO3 Div1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": soC3D1Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "soc3d2" : {
        "name": "Station Officer 3 Div 2",
        "shortname": "SO3 Div2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": soC3D2Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "smc4d1" : {
        "name": "Station Master 4 Div 1",
        "shortname": "SM4 Div1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": smC4D1Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "smc4d2" : {
        "name": "Station Master 4 Div 2",
        "shortname": "SM4 Div2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": smC4D2Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "smc5d1" : {
        "name": "Station Master 5 Div 1",
        "shortname": "SM5 Div1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": smC5D1Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "smc5d2" : {
        "name": "Station Master 5 Div 2",
        "shortname": "SM5 Div2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": smC5D2Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "smc6d1" : {
        "name": "Station Master 6 Div 1",
        "shortname": "SM6 Div1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": smC6D1Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    }
    ,
    "smc6d2" : {
        "name": "Station Master 6 Div 2",
        "shortname": "SM6 Div2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": smC6D2Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "smc7d1" : {
        "name": "Station Master 7 Div 1",
        "shortname": "SM7 Div1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": smC7D1Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "smc7d2" : {
        "name": "Station Master 7 Div 2",
        "shortname": "SM7 Div2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": smC7D2Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "smc8d1" : {
        "name": "Station Master 8 Div 1",
        "shortname": "SM8 Div1",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": smC8D1Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    },
    "smc8d2" : {
        "name": "Station Master 8 Div 2",
        "shortname": "SM8 Div2",
        "payCode": "",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2019",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": smC8D2Rates,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "",
        "endDate": "2024-03-09"
    }
}

const higherDutiesGroups = {
    "stations eba 2023": [
        "traineeStationAssistant",
        "stationAssistant",
        "stationOfficer",
        "seniorStationOfficer",
        "traineeStationMaster",
        "stationMaster",
        "seniorStationMaster"
    ],
    "stations eba 2019": [
        "sac1y1",
        "sac1y2",
        "sac1y3",
        "sac2y1",
        "sac2y2",
        "sac2y3",
        "sac3y1",
        "sac3y2",
        "sac3y3",
        "lsay1",
        "lsay2",
        "lsay3",
        "soc1d1",
        "soc1d2",
        "soc2d1",
        "soc2d2",
        "soc3d1",
        "soc3d2",
        "smc4d1",
        "smc4d2",
        "smc5d1",
        "smc5d2",
        "smc6d1",
        "smc6d2",
        "smc7d1",
        "smc7d2",
        "smc8d1",
        "smc8d2"
    ],
    "drivers": [
        "conversion",
        "trainee",
        "level1",
        "spot",
        "so8",
        "so9",
        "so10",
        "so11",
        "so12",
        "so13"
    ],
    "signallers": [
        "sigso2",
        "sigso3",
        "acsm5",
        "acsm6",
        "dc"
    ],
    "metrol": [
        "tc1",
        "tc2",
        "tc3",
        "tc4",
        "fc",
        "pids1",
        "pids2"
    ]
}