//grades.js
//version 1.16
//defines each grade and their parameters.
const opsExcessHoursThreshold = 4
const driverExcessHoursThreshold = 3

const grades = {
    //DRIVING GRADES
    "spot" : {
        "name" : "Qualified Driver (SPOT)",
        "shortname": "SPOT",
        "payCode": "OJJ",
        "group": "Driver",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  true,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OJJ,
        "earlyShiftRates": earlyShiftRatesLoco,
        "afternoonShiftRates": afternoonShiftRatesLoco,
        "nightShiftRates": nightShiftRatesLoco,
        "colour": "#4691db",
        "startDate": "",
        "endDate": ""
    },
    "level1" : {
        "name" : "Train Driver Level 1",
        "shortname": "TD Lvl 1",
        "payCode": "OJH",
        "group": "Driver",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  true,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OJH,
        "earlyShiftRates": earlyShiftRatesLoco,
        "afternoonShiftRates": afternoonShiftRatesLoco,
        "nightShiftRates": nightShiftRatesLoco,
        "colour": "rgb(114, 99, 191)",
        "startDate": "",
        "endDate": ""
    },
    "trainee" : {
        "name" : "Trainee Driver",
        "shortname": "Trainee",
        "payCode": "OJG",
        "group": "Driver",
        "ordinaryDays" : 10,
        "ordinaryHours" : 7.6,
        "ddo" : false,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OJG,
        "earlyShiftRates": earlyShiftRatesLoco,
        "afternoonShiftRates": afternoonShiftRatesLoco,
        "nightShiftRates": nightShiftRatesLoco,
        "colour": "rgb(56, 149, 149)",
        "startDate": "",
        "endDate": ""
    },
    "conversion" : {
        "name" : "Conversion Trainee Driver",
        "shortname": "Conversion",
        "payCode": "OJB",
        "group": "Driver",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  true,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OJB,
        "earlyShiftRates": earlyShiftRatesLoco,
        "afternoonShiftRates": afternoonShiftRatesLoco,
        "nightShiftRates": nightShiftRatesLoco,
        "colour": "rgb(207, 133, 50)",
        "startDate": "",
        "endDate": ""
    },
    "so8" : {
        "name" : "Train Services Officer SO-8",
        "shortname": "TSO SO-8",
        "payCode": "OGH",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGH,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    "so9" : {
        "name" : "Train Services Officer SO-9",
        "shortname": "TSO SO-9",
        "payCode": "OGI",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGI,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    "so10" : {
        "name" : "Train Services Officer SO-10",
        "shortname": "TSO SO-10",
        "payCode": "OGJ",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGJ,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    "so11" : {
        "name" : "Train Services Officer SO-11",
        "shortname": "TSO SO-11",
        "payCode": "OGK",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGK,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    "so12" : {
        "name" : "Train Services Officer SO-12",
        "shortname": "TSO SO-12",
        "payCode": "OGL",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGL,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    "so13" : {
        "name" : "Train Services Officer SO-13",
        "shortname": "TSO SO-13",
        "payCode": "OGM",
        "group": "Train Services",
        "ordinaryDays" : 10,
        "ordinaryHours" : 8,
        "ddo" : true,
        "drivingGrade": true,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "drivers",
        "suburbanAllowance" :  false,
        "excessHoursThreshold": driverExcessHoursThreshold,
        "payRates": OGM,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "#606060",
        "startDate": "",
        "endDate": ""
    },
    //DAOS AND ROSTERS
    "dao" : {
        "name" : "Driver Allocation Officer",
        "shortname": "DAO",
        "payCode": "OGB",
        "group": "Train Crew Rostering",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "rosters",
        "suburbanAllowance":  false,
        "excessHoursThreshold": 4,
        "payRates": OGB,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(157, 29, 29)",
        "startDate": "",
        "endDate": ""
    },
    "daoteamleader" : {
        "name": "DAO Team Leader",
        "shortname": "DAO TL",
        "payCode": "OGI",
        "group": "Train Crew Rostering",
        "ordinaryDays": 9,
        "ordinaryHours": 8.5,
        "ddo": false,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "rosters",
        "suburbanAllowance":  false,
        "excessHoursThreshold": 4,
        "payRates": OGI,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(157, 29, 29)",
        "startDate": "",
        "endDate": ""
    },
    "rostersadministratordiv1" : {
        "name": "Rosters Administrator Div 1",
        "shortname": "RA div1",
        "payCode": "OEN",
        "group": "Train Crew Rostering",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "rosters",
        "suburbanAllowance":  false,
        "excessHoursThreshold": 4,
        "payRates": OEN,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(157, 29, 29)",
        "startDate": "",
        "endDate": ""
    },
    "rostersadministratordiv2" : {
        "name": "Rosters Administrator Div 2",
        "shortname": "RA div2",
        "payCode": "OEO",
        "group": "Train Crew Rostering",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "rosters",
        "suburbanAllowance":  false,
        "excessHoursThreshold": 4,
        "payRates": OEO,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(157, 29, 29)",
        "startDate": "",
        "endDate": ""
    },
    "driverrosters" : {
        "name": "Driver Roster Planner",
        "shortname": "DRP",
        "payCode": "OGD",
        "group": "Train Crew Rostering",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "rosters",
        "suburbanAllowance":  false,
        "excessHoursThreshold": 4,
        "payRates": OGD,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(157, 29, 29)",
        "startDate": "",
        "endDate": ""
    },
    "driverrostercoordinator" : {
        "name": "Driver Roster Coordinator",
        "shortname": "DRC",
        "payCode": "OGE",
        "group": "Train Crew Rostering",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "rosters",
        "suburbanAllowance":  false,
        "excessHoursThreshold": 4,
        "payRates": OGE,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(157, 29, 29)",
        "startDate": "",
        "endDate": ""
    },
    "driverrosterteamleader" : {
        "name": "Driver Roster Team Leader",
        "shortname": "Rosters TL",
        "payCode": "OGG",
        "group": "Train Crew Rostering",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "rosters",
        "suburbanAllowance":  false,
        "excessHoursThreshold": 4,
        "payRates": OGG,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(157, 29, 29)",
        "startDate": "",
        "endDate": ""
    },
    
    //SIGNALLING GRADES
    "sigso2" : {
        "name": "Signaller - Reliever (entry)",
        "shortname": "Sig Rel 1",
        "payCode": "OAO",
        "group": "Signallers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "signallers",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAO,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "sigso3" : {
        "name": "Signaller - Reliever",
        "shortname": "Sig Rel 2",
        "payCode": "OAQ",
        "group": "Signallers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "signallers",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAQ,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "acsm5" : {
        "name": "Area Controller (entry)",
        "shortname": "AC Entry",
        "payCode": "OAB",
        "group": "Signallers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "signallers",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAB,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "acsm6" : {
        "name": "Area Controller (complex)",
        "shortname": "AC Complex",
        "payCode": "OAD",
        "group": "Signallers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "signallers",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAD,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "dc" : {
        "name": "Depot Controller",
        "shortname": "DC",
        "payCode": "OAF",
        "group": "Signallers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "signallers",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAF,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },

    //TRAIN CONTROLLERS
    "tc1" : {
        "name": "Train Controller 1",
        "shortname": "TC1",
        "payCode": "OAH",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAH,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "tc2" : {
        "name": "Train Controller 2",
        "shortname": "TC2",
        "payCode": "OAI",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAI,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "tc3" : {
        "name": "Train Controller 3",
        "shortname": "TC3",
        "payCode": "OAJ",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAJ,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "tc4" : {
        "name": "Train Controller 4",
        "shortname": "TC4",
        "payCode": "OAL",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAL,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "fc" : {
        "name": "Fleet Controller",
        "shortname": "Fleet",
        "payCode": "OAK",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAK,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "snc" : {
        "name": "Senior Network Controller",
        "shortname": "SNC",
        "payCode": "OGM",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OGM,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "pids1" : {
        "name": "PIDS Operator Div1",
        "shortname": "PIDS1",
        "payCode": "OAS",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAS,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "pids2" : {
        "name": "PIDS Operator Div2",
        "shortname": "PIDS2",
        "payCode": "OAR",
        "group": "METROL",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": false,
        "relievingExpenses": false,
        "higherDutiesGroup": "metrol",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OAR,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(39, 121, 66)",
        "startDate": "2024-03-10",
        "endDate": ""
    },

    //STATIONS
    "traineeStationAssistant" : {
        "name": "Trainee Station Assistant",
        "shortname": "Trainee SA",
        "payCode": "OBK",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OBK,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "stationAssistant" : {
        "name": "Station Assistant",
        "shortname": "SA",
        "payCode": "OBL",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OBL,
        "earlyShiftRates": earlyShiftRatesTPW,
        "afternoonShiftRates": afternoonShiftRatesTPW,
        "nightShiftRates": nightShiftRatesTPW,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "stationOfficer" : {
        "name": "Station Officer",
        "shortname": "SO",
        "payCode": "OBU",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OBU,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "seniorStationOfficer" : {
        "name": "Senior Station Officer",
        "shortname": "Senior SO",
        "payCode": "OBW",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OBW,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "traineeStationMaster" : {
        "name": "Trainee Station Master",
        "shortname": "Trainee SM",
        "payCode": "OCB",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OCB,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "stationMaster" : {
        "name": "Station Master",
        "shortname": "SM",
        "payCode": "OCF",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OCF,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "seniorStationMaster" : {
        "name": "Senior Station Master",
        "shortname": "Senior SM",
        "payCode": "OCJ",
        "group": "Stations",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "stations eba 2023",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": OCJ,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(19, 49, 96)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "aoy1" : {
        "name": "Authorised Officer Year 1",
        "shortname": "AO Year 1",
        "payCode": "ODB",
        "group": "Authorised Officers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "ao",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": ODB,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(42, 48, 72)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "aoy2" : {
        "name": "Authorised Officer Year 2",
        "shortname": "AO Year 2",
        "payCode": "ODD",
        "group": "Authorised Officers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "ao",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": ODD,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(42, 48, 72)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "aoy3" : {
        "name": "Authorised Officer Year 3",
        "shortname": "AO Year 3",
        "payCode": "ODE",
        "group": "Authorised Officers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "ao",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": ODE,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(42, 48, 72)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "aocl" : {
        "name": "Authorised Officer Crew Leader",
        "shortname": "AO CL",
        "payCode": "ODF",
        "group": "Authorised Officers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "ao",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": ODF,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(42, 48, 72)",
        "startDate": "2024-03-10",
        "endDate": ""
    },
    "aotl" : {
        "name": "Authorised Officer Team Leader",
        "shortname": "AO TL",
        "payCode": "ODG",
        "group": "Authorised Officers",
        "ordinaryDays": 10,
        "ordinaryHours": 8,
        "ddo": true,
        "drivingGrade": false,
        "suburbanGroupWorking": true,
        "relievingExpenses": true,
        "higherDutiesGroup": "ao",
        "suburbanAllowance":  false,
        "excessHoursThreshold": opsExcessHoursThreshold,
        "payRates": ODG,
        "earlyShiftRates": earlyShiftRatesSal,
        "afternoonShiftRates": afternoonShiftRatesSal,
        "nightShiftRates": nightShiftRatesSal,
        "colour": "rgb(42, 48, 72)",
        "startDate": "2024-03-10",
        "endDate": ""
    }
}

const higherDutiesGroups = {
    "stations eba 2019": [
        "sac1y1",
        "sac1y2",
        "sac1y3",
        "sac2y1",
        "sac2y2",
        "sac2y3",
        "sac3y1",
        "sac3y2",
        "sac3y3",
        "lsay1",
        "lsay2",
        "lsay3",
        "soc1d1",
        "soc1d2",
        "soc2d1",
        "soc2d2",
        "soc3d1",
        "soc3d2",
        "smc4d1",
        "smc4d2",
        "smc5d1",
        "smc5d2",
        "smc6d1",
        "smc6d2",
        "smc7d1",
        "smc7d2",
        "smc8d1",
        "smc8d2"
    ],
    "ao": [
       "aoy1",
       "aoy2",
       "aoy3",
       "aocl",
       "aotl"
    ],
    "drivers": [
        "conversion",
        "trainee",
        "level1",
        "spot",
        "so8",
        "so9",
        "so10",
        "so11",
        "so12",
        "so13"
    ],
    "rosters": [
        "rostersadministratordiv1",
        "rostersadministratordiv2",
        "dao",
        "daoteamleader",
        "driverrosters",
        "driverrostercoordinator",
        "driverrosterteamleader"
    ],
    "signallers": [
        "sigso2",
        "sigso3",
        "acsm5",
        "acsm6",
        "dc"
    ],
    "metrol": [
        "tc1",
        "tc2",
        "tc3",
        "tc4",
        "fc",
        "snc",
        "pids1",
        "pids2"
    ]
}